apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iwkaykx7s-python
  janus-idp.io/tekton: iwkaykx7s-python
  backstage.io/kubernetes-id: iwkaykx7s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iwkaykx7s-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
